// Production Configuration
// This file is generated during deployment with environment variables
// DO NOT edit this file manually - it's auto-generated

window.ENV_CONFIG = {
    // Contentful Configuration
    CONTENTFUL_SPACE_ID: 'your-space-id-here',
    CONTENTFUL_ACCESS_TOKEN: 'your-access-token-here',
    CONTENTFUL_MANAGEMENT_TOKEN: 'your-management-token-here',
    CONTENTFUL_ENVIRONMENT: 'master',
    
    // Site Configuration
    SITE_URL: 'https://smforge.com',
    SITE_NAME: 'SmartForge Polymers',
    SITE_DESCRIPTION: 'Revolutionizing microfabrication with bold tech innovation',
    
    // Environment
    NODE_ENV: 'production'
};

console.log('🚀 Production configuration loaded');
console.log('📝 Environment variables injected from deployment platform');