#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

// Read environment variables
const envVars = {
    CONTENTFUL_SPACE_ID: process.env.CONTENTFUL_SPACE_ID || 'your-space-id-here',
    CONTENTFUL_ACCESS_TOKEN: process.env.CONTENTFUL_ACCESS_TOKEN || 'your-access-token-here',
    CONTENTFUL_MANAGEMENT_TOKEN: process.env.CONTENTFUL_MANAGEMENT_TOKEN || 'your-management-token-here',
    CONTENTFUL_ENVIRONMENT: process.env.CONTENTFUL_ENVIRONMENT || 'master',
    SITE_URL: process.env.SITE_URL || 'https://smforge.com',
    SITE_NAME: process.env.SITE_NAME || 'SmartForge Polymers',
    SITE_DESCRIPTION: process.env.SITE_DESCRIPTION || 'Revolutionizing microfabrication with bold tech innovation',
    NODE_ENV: process.env.NODE_ENV || 'production'
};

// Generate production config
const prodConfigContent = `// Production Configuration
// This file is generated during deployment with environment variables
// DO NOT edit this file manually - it's auto-generated

window.ENV_CONFIG = {
    // Contentful Configuration
    CONTENTFUL_SPACE_ID: '${envVars.CONTENTFUL_SPACE_ID}',
    CONTENTFUL_ACCESS_TOKEN: '${envVars.CONTENTFUL_ACCESS_TOKEN}',
    CONTENTFUL_MANAGEMENT_TOKEN: '${envVars.CONTENTFUL_MANAGEMENT_TOKEN}',
    CONTENTFUL_ENVIRONMENT: '${envVars.CONTENTFUL_ENVIRONMENT}',
    
    // Site Configuration
    SITE_URL: '${envVars.SITE_URL}',
    SITE_NAME: '${envVars.SITE_NAME}',
    SITE_DESCRIPTION: '${envVars.SITE_DESCRIPTION}',
    
    // Environment
    NODE_ENV: '${envVars.NODE_ENV}'
};

console.log('🚀 Production configuration loaded');
console.log('📝 Environment variables injected from deployment platform');
`;

// Write the production config file
fs.writeFileSync(path.join(__dirname, 'js', 'prod-config.js'), prodConfigContent);

console.log('✅ Production config generated successfully');
console.log('📝 Environment variables injected:', Object.keys(envVars).join(', '));
